### ISSUE TITLE
Cholesterol

### ISSUE THREAD

**Issue by Kimiatuzzaman** [Intelligent-System-Lab/food-recommendation#7] opened 2021-11-19 01:58 UTC
The issue with cholesterol is a bit complicated. There are actually two types of cholesterol: good ones and bad ones. In the meal when ever you select a protein food it comes with cholesterol and in the app. Such as for each egg it adds 119 points in cholesterol same goes for poultry, meat or fish. But eventually is shows high even if you just consumed only good kind cholesterol such as those come with chicken/ eggs.

**Comment by wordhulhasan** [comment] 2021-12-17 20:32
Not Relevant to this project. The issue is from User App. Closing this issue here.

**Closed by wordhulhasan** 2021-12-17 20:32 UTC
